import { initializeApp, cert } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import * as dotenv from 'dotenv';
import * as path from 'path';
import * as fs from 'fs';

dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const serviceAccountPath = process.env.FIREBASE_SERVICE_ACCOUNT_PATH ?? './service-account.json';
const projectId = process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID;

if (!fs.existsSync(serviceAccountPath)) {
  console.error(`Service account file not found at: ${serviceAccountPath}`);
  console.error('Download it from Firebase Console → Project Settings → Service Accounts');
  process.exit(1);
}

initializeApp({
  credential: cert(serviceAccountPath),
  projectId,
});

const db = getFirestore();

const DOCTORS = [
  // ── Dhaka ──────────────────────────────────────────────────────────────────
  {
    id: 'doc-001',
    nameEn: 'Dr. Rafiqul Islam',
    nameBn: 'ডা. রফিকুল ইসলাম',
    qualifications: ['MBBS', 'MD (Cardiology)', 'FACC'],
    bmdcReg: 'A-12345',
    specialty: 'Cardiology',
    hospitalNameEn: 'National Heart Foundation Hospital',
    hospitalNameBn: 'জাতীয় হৃদরোগ ইনস্টিটিউট',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.7801, lng: 90.3567 },
    consultationFee: 1500,
    telemedicineFee: 1000,
    availableDays: ['Sat', 'Sun', 'Mon', 'Tue'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.8,
    reviewCount: 124,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Senior consultant cardiologist with 18 years of experience in interventional cardiology.',
  },
  {
    id: 'doc-002',
    nameEn: 'Dr. Nasreen Akter',
    nameBn: 'ডা. নাসরীন আক্তার',
    qualifications: ['MBBS', 'FCPS (Gynecology & Obstetrics)'],
    bmdcReg: 'A-23456',
    specialty: 'Gynecology',
    hospitalNameEn: 'Evercare Hospital Dhaka',
    hospitalNameBn: 'এভারকেয়ার হাসপাতাল ঢাকা',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.8103, lng: 90.4125 },
    consultationFee: 2000,
    telemedicineFee: 1200,
    availableDays: ['Sun', 'Mon', 'Wed', 'Thu'],
    timeSlots: ['10:00', '10:30', '11:00', '11:30', '14:00', '14:30', '15:00', '15:30'],
    avatarUrl: null,
    ratingAvg: 4.9,
    reviewCount: 87,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Specialist in high-risk pregnancy and minimally invasive gynecological procedures.',
  },
  {
    id: 'doc-003',
    nameEn: 'Dr. Mahmud Hasan',
    nameBn: 'ডা. মাহমুদ হাসান',
    qualifications: ['MBBS', 'MD (Medicine)', 'MRCP (UK)'],
    bmdcReg: 'A-34567',
    specialty: 'General Medicine',
    hospitalNameEn: 'Square Hospital',
    hospitalNameBn: 'স্কয়ার হাসপাতাল',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.7512, lng: 90.3752 },
    consultationFee: 1200,
    telemedicineFee: 800,
    availableDays: ['Sat', 'Sun', 'Tue', 'Wed'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.7,
    reviewCount: 203,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Internal medicine specialist with expertise in tropical diseases, dengue, and typhoid management.',
  },
  {
    id: 'doc-004',
    nameEn: 'Dr. Farida Khanam',
    nameBn: 'ডা. ফরিদা খানম',
    qualifications: ['MBBS', 'FCPS (Pediatrics)', 'DCH'],
    bmdcReg: 'A-45678',
    specialty: 'Pediatrics',
    hospitalNameEn: 'Dhaka Shishu Hospital',
    hospitalNameBn: 'ঢাকা শিশু হাসপাতাল',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.7380, lng: 90.3960 },
    consultationFee: 1000,
    telemedicineFee: 700,
    availableDays: ['Sun', 'Mon', 'Tue', 'Thu'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.9,
    reviewCount: 312,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Pediatric specialist focusing on newborn care, childhood vaccinations, and growth disorders.',
  },
  {
    id: 'doc-005',
    nameEn: 'Dr. Anwar Hossain',
    nameBn: 'ডা. আনোয়ার হোসেন',
    qualifications: ['MBBS', 'MS (Orthopedics)', 'FRCS'],
    bmdcReg: 'A-56789',
    specialty: 'Orthopedics',
    hospitalNameEn: 'BSMMU (PG Hospital)',
    hospitalNameBn: 'বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয়',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.7385, lng: 90.3955 },
    consultationFee: 1500,
    telemedicineFee: 900,
    availableDays: ['Sat', 'Mon', 'Wed'],
    timeSlots: ['14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30'],
    avatarUrl: null,
    ratingAvg: 4.6,
    reviewCount: 156,
    isVerified: true,
    telemedicineAvailable: false,
    isAvailable: true,
    bio: 'Joint replacement surgeon with expertise in knee and hip arthroplasty.',
  },
  {
    id: 'doc-006',
    nameEn: 'Dr. Shahnaz Parvin',
    nameBn: 'ডা. শাহনাজ পারভীন',
    qualifications: ['MBBS', 'DDV (Dermatology)'],
    bmdcReg: 'A-67890',
    specialty: 'Dermatology',
    hospitalNameEn: 'Labaid Specialized Hospital',
    hospitalNameBn: 'লাবএইড স্পেশালাইজড হাসপাতাল',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.7462, lng: 90.3741 },
    consultationFee: 800,
    telemedicineFee: 600,
    availableDays: ['Sun', 'Tue', 'Thu', 'Sat'],
    timeSlots: ['10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '16:00', '16:30'],
    avatarUrl: null,
    ratingAvg: 4.5,
    reviewCount: 89,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Dermatologist specializing in eczema, psoriasis, acne, and cosmetic procedures.',
  },
  // ── Chittagong ────────────────────────────────────────────────────────────
  {
    id: 'doc-007',
    nameEn: 'Dr. Kamal Uddin Ahmed',
    nameBn: 'ডা. কামাল উদ্দিন আহমেদ',
    qualifications: ['MBBS', 'FCPS (Medicine)', 'MD (Neurology)'],
    bmdcReg: 'A-78901',
    specialty: 'Neurology',
    hospitalNameEn: 'Chittagong Medical College Hospital',
    hospitalNameBn: 'চট্টগ্রাম মেডিকেল কলেজ হাসপাতাল',
    division: 'Chittagong',
    district: 'Chittagong',
    coordinates: { lat: 22.3569, lng: 91.8329 },
    consultationFee: 1200,
    telemedicineFee: 800,
    availableDays: ['Sat', 'Sun', 'Mon', 'Wed'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.7,
    reviewCount: 98,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Neurologist treating stroke, epilepsy, Parkinson\'s disease, and migraine.',
  },
  {
    id: 'doc-008',
    nameEn: 'Dr. Roksana Begum',
    nameBn: 'ডা. রোকসানা বেগম',
    qualifications: ['MBBS', 'FCPS (Gynecology)'],
    bmdcReg: 'A-89012',
    specialty: 'Gynecology',
    hospitalNameEn: 'Evercare Hospital Chattogram',
    hospitalNameBn: 'এভারকেয়ার হাসপাতাল চট্টগ্রাম',
    division: 'Chittagong',
    district: 'Chittagong',
    coordinates: { lat: 22.3490, lng: 91.8349 },
    consultationFee: 1500,
    telemedicineFee: 900,
    availableDays: ['Sun', 'Mon', 'Tue', 'Thu'],
    timeSlots: ['10:00', '10:30', '11:00', '11:30', '14:00', '14:30', '15:00', '15:30'],
    avatarUrl: null,
    ratingAvg: 4.8,
    reviewCount: 67,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Ob-Gyn specialist with focus on maternal health and laparoscopic surgery.',
  },
  {
    id: 'doc-009',
    nameEn: 'Dr. Shahidul Haq',
    nameBn: 'ডা. শাহিদুল হক',
    qualifications: ['MBBS', 'MS (ENT)'],
    bmdcReg: 'A-90123',
    specialty: 'ENT',
    hospitalNameEn: 'Park View Hospital Chittagong',
    hospitalNameBn: 'পার্ক ভিউ হাসপাতাল চট্টগ্রাম',
    division: 'Chittagong',
    district: 'Chittagong',
    coordinates: { lat: 22.3600, lng: 91.8200 },
    consultationFee: 900,
    telemedicineFee: 600,
    availableDays: ['Sat', 'Sun', 'Mon', 'Wed'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '15:00', '15:30'],
    avatarUrl: null,
    ratingAvg: 4.4,
    reviewCount: 45,
    isVerified: true,
    telemedicineAvailable: false,
    isAvailable: true,
    bio: 'ENT surgeon specializing in endoscopic sinus surgery and hearing disorders.',
  },
  // ── Sylhet ────────────────────────────────────────────────────────────────
  {
    id: 'doc-010',
    nameEn: 'Dr. Salim Reza',
    nameBn: 'ডা. সালিম রেজা',
    qualifications: ['MBBS', 'FCPS (Medicine)'],
    bmdcReg: 'A-01234',
    specialty: 'General Medicine',
    hospitalNameEn: 'MAG Osmani Medical College Hospital',
    hospitalNameBn: 'ওসমানী মেডিকেল কলেজ হাসপাতাল',
    division: 'Sylhet',
    district: 'Sylhet',
    coordinates: { lat: 24.8988, lng: 91.875 },
    consultationFee: 700,
    telemedicineFee: 500,
    availableDays: ['Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.6,
    reviewCount: 178,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'General physician with over 12 years of experience in internal medicine.',
  },
  {
    id: 'doc-011',
    nameEn: 'Dr. Ayesha Siddiqua',
    nameBn: 'ডা. আয়েশা সিদ্দিকা',
    qualifications: ['MBBS', 'DCH', 'FCPS (Pediatrics)'],
    bmdcReg: 'A-11235',
    specialty: 'Pediatrics',
    hospitalNameEn: 'Mount Adora Hospital Sylhet',
    hospitalNameBn: 'মাউন্ট আডোরা হাসপাতাল',
    division: 'Sylhet',
    district: 'Sylhet',
    coordinates: { lat: 24.9045, lng: 91.8685 },
    consultationFee: 800,
    telemedicineFee: 600,
    availableDays: ['Sun', 'Mon', 'Tue', 'Thu'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.8,
    reviewCount: 134,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Pediatrician with special interest in neonatal care and childhood nutrition.',
  },
  // ── Rajshahi ──────────────────────────────────────────────────────────────
  {
    id: 'doc-012',
    nameEn: 'Dr. Mizanur Rahman',
    nameBn: 'ডা. মিজানুর রহমান',
    qualifications: ['MBBS', 'MS (Orthopedics)'],
    bmdcReg: 'A-22346',
    specialty: 'Orthopedics',
    hospitalNameEn: 'Rajshahi Medical College Hospital',
    hospitalNameBn: 'রাজশাহী মেডিকেল কলেজ হাসপাতাল',
    division: 'Rajshahi',
    district: 'Rajshahi',
    coordinates: { lat: 24.3636, lng: 88.599 },
    consultationFee: 800,
    telemedicineFee: 0,
    availableDays: ['Sat', 'Sun', 'Mon'],
    timeSlots: ['14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30'],
    avatarUrl: null,
    ratingAvg: 4.5,
    reviewCount: 56,
    isVerified: true,
    telemedicineAvailable: false,
    isAvailable: true,
    bio: 'Orthopedic surgeon specializing in trauma surgery and sports injuries.',
  },
  {
    id: 'doc-013',
    nameEn: 'Dr. Lutfun Nahar',
    nameBn: 'ডা. লুৎফুন নাহার',
    qualifications: ['MBBS', 'FCPS (Gynecology)'],
    bmdcReg: 'A-33457',
    specialty: 'Gynecology',
    hospitalNameEn: 'Popular Medical Centre Rajshahi',
    hospitalNameBn: 'পপুলার মেডিকেল সেন্টার রাজশাহী',
    division: 'Rajshahi',
    district: 'Rajshahi',
    coordinates: { lat: 24.369, lng: 88.601 },
    consultationFee: 600,
    telemedicineFee: 400,
    availableDays: ['Sun', 'Mon', 'Tue', 'Wed'],
    timeSlots: ['10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '16:00', '16:30'],
    avatarUrl: null,
    ratingAvg: 4.6,
    reviewCount: 89,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Gynecologist with expertise in menstrual disorders and infertility treatment.',
  },
  // ── Khulna ────────────────────────────────────────────────────────────────
  {
    id: 'doc-014',
    nameEn: 'Dr. Harunur Rashid',
    nameBn: 'ডা. হারুনুর রশিদ',
    qualifications: ['MBBS', 'MD (Gastroenterology)'],
    bmdcReg: 'A-44568',
    specialty: 'Gastroenterology',
    hospitalNameEn: 'Khulna Medical College Hospital',
    hospitalNameBn: 'খুলনা মেডিকেল কলেজ হাসপাতাল',
    division: 'Khulna',
    district: 'Khulna',
    coordinates: { lat: 22.8456, lng: 89.5403 },
    consultationFee: 900,
    telemedicineFee: 600,
    availableDays: ['Sat', 'Sun', 'Mon', 'Thu'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.7,
    reviewCount: 72,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Gastroenterologist specializing in liver diseases, H. pylori, and endoscopic procedures.',
  },
  {
    id: 'doc-015',
    nameEn: 'Dr. Shirin Akter',
    nameBn: 'ডা. শিরিন আক্তার',
    qualifications: ['MBBS', 'DDV', 'MCPS (Dermatology)'],
    bmdcReg: 'A-55679',
    specialty: 'Dermatology',
    hospitalNameEn: 'Gazi Medical College Hospital Khulna',
    hospitalNameBn: 'গাজী মেডিকেল কলেজ হাসপাতাল',
    division: 'Khulna',
    district: 'Khulna',
    coordinates: { lat: 22.8374, lng: 89.5473 },
    consultationFee: 700,
    telemedicineFee: 500,
    availableDays: ['Sun', 'Mon', 'Wed', 'Thu'],
    timeSlots: ['10:00', '10:30', '11:00', '11:30', '16:00', '16:30', '17:00', '17:30'],
    avatarUrl: null,
    ratingAvg: 4.4,
    reviewCount: 43,
    isVerified: false,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Skin specialist treating fungal infections, allergies, vitiligo, and hair disorders.',
  },
  // Additional doctors for variety
  {
    id: 'doc-016',
    nameEn: 'Dr. Tariqul Islam',
    nameBn: 'ডা. তারিকুল ইসলাম',
    qualifications: ['MBBS', 'FCPS (Psychiatry)', 'MRCPsych'],
    bmdcReg: 'A-66780',
    specialty: 'Psychiatry',
    hospitalNameEn: 'NIMH (National Institute of Mental Health)',
    hospitalNameBn: 'জাতীয় মানসিক স্বাস্থ্য ইনস্টিটিউট',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.7760, lng: 90.3682 },
    consultationFee: 1500,
    telemedicineFee: 1200,
    availableDays: ['Sun', 'Mon', 'Tue', 'Thu'],
    timeSlots: ['10:00', '10:30', '11:00', '11:30', '14:00', '14:30', '15:00', '15:30'],
    avatarUrl: null,
    ratingAvg: 4.8,
    reviewCount: 61,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Psychiatrist specializing in depression, anxiety disorders, PTSD, and addiction medicine.',
  },
  {
    id: 'doc-017',
    nameEn: 'Dr. Wahidur Rahman',
    nameBn: 'ডা. ওয়াহিদুর রহমান',
    qualifications: ['MBBS', 'DO (Ophthalmology)', 'FRCS (Ed)'],
    bmdcReg: 'A-77891',
    specialty: 'Ophthalmology',
    hospitalNameEn: 'National Eye Care Centre',
    hospitalNameBn: 'জাতীয় চক্ষু বিজ্ঞান ইনস্টিটিউট',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.7552, lng: 90.3822 },
    consultationFee: 1000,
    telemedicineFee: 0,
    availableDays: ['Sat', 'Sun', 'Wed'],
    timeSlots: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30'],
    avatarUrl: null,
    ratingAvg: 4.7,
    reviewCount: 93,
    isVerified: true,
    telemedicineAvailable: false,
    isAvailable: true,
    bio: 'Ophthalmologist with expertise in cataract surgery, glaucoma management, and diabetic retinopathy.',
  },
  {
    id: 'doc-018',
    nameEn: 'Dr. Nazmul Huda',
    nameBn: 'ডা. নজমুল হুদা',
    qualifications: ['MBBS', 'MS (Urology)'],
    bmdcReg: 'A-88902',
    specialty: 'Urology',
    hospitalNameEn: 'United Hospital Dhaka',
    hospitalNameBn: 'ইউনাইটেড হাসপাতাল ঢাকা',
    division: 'Dhaka',
    district: 'Dhaka',
    coordinates: { lat: 23.8009, lng: 90.4133 },
    consultationFee: 1500,
    telemedicineFee: 1000,
    availableDays: ['Sun', 'Mon', 'Tue', 'Wed'],
    timeSlots: ['14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30'],
    avatarUrl: null,
    ratingAvg: 4.6,
    reviewCount: 51,
    isVerified: true,
    telemedicineAvailable: true,
    isAvailable: true,
    bio: 'Urologist specializing in kidney stones, prostate disorders, and laparoscopic urology.',
  },
];

async function seed() {
  const batch = db.batch();
  for (const doctor of DOCTORS) {
    const { id, ...data } = doctor;
    const ref = db.collection('doctors').doc(id);
    batch.set(ref, {
      ...data,
      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });
  }
  await batch.commit();
  console.log(`✅ Seeded ${DOCTORS.length} doctors successfully`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
